nhn/tui.chart

src/js/models/scaleData/coordinateScaleCalculator.js, src/js/models/scaleData/scaleDataMaker.js, src/js/models/scaleData/scaleDataModel.js, test/models/scaleData/coordinateScaleCalculator.spec.js
- Sometimes the totals in the chart are sometimes out of the chart. #59
(시리즈 영역의 showLabel 옵션이 true일때 Label이 시리즈 영역 밖으로 벗어나 보이는 부분 수정)
- http://10.78.9.21:8082/examples/example02-01-column-chart-basic.html
=> fix: totals in the chart are sometimes out of the chart(fix #59)

src/js/components/tooltips/groupTooltip.js, src/js/components/tooltips/tooltipBase.js, test/components/tooltips/groupTooltip.spec.js
- An error appears in the group tooltip with no legend area. #51 
(legend.visible 옵션이 false일때 그룹툴팁이 동작하지 않음)
- http://10.78.9.21:8082/examples/example02-04-column-chart-group-stack.html
=> fix: error in group tooltip with no legend area (fix #51)

src/js/plugins/raphaelAreaChart.js, src/js/plugins/raphaelLineChart.js, src/js/plugins/raphaelLineTypeBase.js, test/plugins/raphaelAreaChart.spec.js, test/plugins/raphaelLineTypeBase.spec.js
- Spline only shows one chart in stacked area demo #63
(스텍 에어리어 차트의 spline옵션을 추가할 경우 값이 하나의 시리즈만 보이는 이슈 수정.)
- http://10.78.9.21:8082/examples/example04-02-area-chart-normal-stack.html
=> fix: Spline only shows one chart in stacked area (fix #63)

src/js/components/mouseEventDetectors/boundsBaseCoordinateModel.js, src/js/components/series/columnChartSeries.js, src/js/const.js, src/js/plugins/raphaelBarChart.js, test/components/mouseEventDetectors/boundsBaseCoordinateModel.spec.js, test/plugins/raphaelBarChart.spec.js
-   If data is 0, the tooltip is not visible.(bar타입 차트에서 데이터가 0인 series는 tooltip이 보이지 않음) #73 
- 값이 0일때 event detector 의 이벤트 감지 바운더리를 앞 뒤로 2px붙여줌.
- 값이 0일때 보이지 않던 컬럼 bar를 희미하게 보이도록 수정.
- http://10.78.9.21:8082/examples/example01-01-bar-chart-basic.html
- http://10.78.9.21:8082/examples/example02-01-column-chart-basic.html
=> fix: even if data is zero, the tooltip show for version 3.0.1

src/js/components/axes/axis.js, src/js/const.js, src/js/models/scaleData/axisDataMaker.js, test/models/scaleData/axisDataMaker.spec.js
-  [Axis tick label alignment, when label is rotated](https://github.nhnent.com/fe/tui.chart/issues/664) #31
- x축 레이블이 카테고리 타입일 경우 가운데 정렬해 주던 부분의 코드 제거
- rotate의 변경 기준에서 XAXIS_LABEL_COMPARE_MARGIN 값을 더해주던 부분을 제거
(레이블이 왼쪽으로 정렬되면서 x축 첫번째 레이블의 시작점이 잘리는 현상이 생기는 이유로 rotate기준을 엄격하게 변경)
- http://10.78.9.21:8082/examples/example04-01-area-chart-basic.html
=> fix: Axis tick label alignment, when label is rotated (#31)

src/js/components/title/title.js, src/js/plugins/raphaelTitleComponent.js, test/plugins/raphaelTitleComponent.spec.js
- title 정렬이 제대로 안되는 부분 수정.
- title의 포지션 left, center, right 의 text-anchor를 각각 start, middle, end로 변경.
- chartWidth 구하는 공식 변경
- (center 정렬 )http://10.78.9.21:8082/examples/example01-01-bar-chart-basic.html
- (right 정렬 )http://10.78.9.21:8082/examples/example07-03-pie-chart-outer-legend.html
=> fix: title align anchor bug

src/js/components/axes/axis.js, test/components/axes/axis.spec.js
- tickInterval 옵션이 auto이면서  마지막 tick이 이전 tick과 너무 붙어 있을때 label이 겹쳐보이는 현상
- label 크기보다 tick간격이 짧을경우 이전 레이블 출력을 생략하여 주도록 변경
- http://10.78.9.21:8081/examples/example08-03-combo-chart-line-and-area.html
=> fix: label overlap when autoInterval option is true

src/js/components/tooltips/normalTooltip.js, src/js/components/tooltips/tooltipBase.js, src/js/plugins/raphaelLineTypeBase.js, test/components/tooltips/normalTooltip.spec.js, test/plugins/raphaelLineTypeBase.spec.js
- #105 radial 차트에 첫번째 값이 툴팁 데이터 값이 깨집니다.
- 방사형 차트의 포지션 값의 마지막 포지션에 해당하는 데이터 값은 실질적으로 index 0 에 해당하는 값임으로
마지막 position 인 경우 데이터를 찾을때는 index 0의 데이터 값을 찾도록 변경함.
- _makeSingleTooltipHtml 메소드의 기능을 새로운 메소드로 분리해 함수 복잡도를 낮춤.
- http://10.78.9.21:8082/examples/example13-01-radial-chart-basic.html
=> fix: radial chart tooltip and dot bug (fix #105)

src/js/models/bounds/seriesCalculator.js, test/models/bounds/seriesCalculator.spec.js
- legend.align 옵션이 'top'이고 chart.title 의 값이 빈 값일때 차트 영역의 끝인 x축 레이블이 잘려보임
- calculateHeight() 메서드에서 시리즈 영역의 높이 계산식을 serise영역의 positionTop 계산식과 비교하여 정확히 맞추어줌
- http://10.78.9.21:8083/examples/example03-01-line-chart-basic.html
=> fix: Invalid calculation of series area

src/js/components/chartExportMenu/chartExportMenu.js, test/components/chartExportMenu/chartExportMenu.spec.js
- 라인차트에서 series영역에 마우스 오버 후 툴팁 image 내보내기시 0바이트의 이미지가 생성되는 버그
- tooltip 내 라인 아이콘을 svg로 그렸기 때문에 container내의 svg selector가 잘못된 svg를 select하는 이슈가 있었음. (컨테이너 바로 1level 아래 있는 chart의 svg를 정확히 select하는 메소드를 만들어서 사용하도록 수정)
=> fix: image export zero size bug in line-chart

src/js/components/series/pieChartSeries.js, test/components/series/pieChartSeries.spec.js
- 파이 차트에서 값이 0인 데이터가 있고 showLabel, showLegend값이 모두 true일때 값이 0이면  레이블 포지션을 다시 계산할 필요가 없으로 계산하지 않도록 if문 안에 조건식을 엄격하게 변경 
- 관련된 테스트 추가
=> fixed pie chart zero raow data and showlabel

karma.conf.js, src/js/components/legends/legend.js, src/js/components/legends/legendModel.js, src/js/const.js, test/components/legends/legend.spec.js
* 글로벌 이벤트로 `changeCheckedLegends`를 추가함.
* getCheckedIndexes() 의 결과 배열 값에서  `empty`값을 `false`로 재정의하여 반환하도록 함.
- 기존에는 checkedIndexes 배열에서 아래와 같이 빈값(empty)일 경우 false로 판단하여 문제가 없었지만
퍼블릭 이벤트로 확장하면서,  최종유저가 사용하는 checkedIndex 배열에 빈값(empty)이 표시되는 
부분은 명시적이지 않음으로 `빈값을 boolean(false)값으로 재정의` 해줌.
```
// [true, empty, true, true] -> [true, false, true, true]
```
- `checkedIndexesMap` 참조를 그대로 노출하면 외부에서 값이 변경될 우려가 있음으로 재가공하여 데이터 변이를 방지
=> feat: add global event for changeCheckedLegends

src/js/chart.js, src/js/themes/themeManager.js, test/themes/themeManager.spec.js
* series.colorByPoint 옵션 (범례가 하나일때 카테고리 별로 색상이 나오도록 하는 옵션) 이 적용되지 않는 부분 수정
1. colorByPoint 옵션 적용중에는 themeManager._getSeriesThemeColorCount 가 카테고리 개수를 반환해야 함 - 재료가 되는 테마의 기본 색상 수가 모자르기 때문에 (원인파악).
2. 잘 되던 시점의 깃헙 로그 찾아서 문제가 되는 부분 확인 하여 원복하고 추가로 `series.colorByPoint` 을 직접 확인하도록 조건문을 강화함.
3. jsdoc에  `series.colorByPoint` 옵션 추가
=> fixed colorByPoint option

src/js/components/mouseEventDetectors/areaTypeDataModel.js, src/js/components/mouseEventDetectors/areaTypeEventDetector.js, test/components/mouseEventDetectors/areaTypeDataModel.spec.js
* 기존 방식은 마우스 포지션에 x, y 좌표 와 데이터 좌표의 거리가 50px 안쪽에 해당하는 데이터 중, 가장 인접한 데이터를 찾기때문에 데이터가 빼곡히 있는 경우 일반적인 동작으로 생각하기에는 원치 않는 데이터의 툴팁이 나오는 경우가 있어서 버그로 인식된다. (원인 파악)
* areatype 차트에서 마우스 포지션에 해당하는 데이터를 찾는 방식을 x 포지션 중심으로 먼저 찾도록 변경
-  마우스 좌표와 데이터 사이의 가로 폭 기준으로 가장 가까운 x좌표 후보군 중에 세로폭 기준에서 다시 찾도록 변경
-- 이슈내용 참고
=> change findData algorithm

src/js/models/scaleData/axisDataMaker.js, test/models/scaleData/axisDataMaker.spec.js
* 위와 같이 가장 오른쪽 카테고리 레이블이 살짝 잘려보임
* x축 전체 폭 계산에 영향을 미치는 y축 영역의 값이 잘못 계산되는 부분 발견하여 수정 
* y축 영역을 계산할때 y축의 오른쪽 보조축이 없을경우에는 항상 0으로 계산되는 버그가 있었음.
=> fix: yAxisAreaWidth incorrect caculate

src/js/components/mouseEventDetectors/areaTypeDataModel.js, src/js/components/mouseEventDetectors/areaTypeEventDetector.js, test/components/mouseEventDetectors/areaTypeDataModel.spec.js
* 라인차트에서 데이터 간격이 조밀한 데이터 탐색의 경우 `x좌표 우선 탐색`이 적용된다. 하지만 데이터에 x,y 좌표를 사용하는 좌표계 라인 차트에서는 위와 같이 한쪽 데이터의 x포지션이 없는 구간일 경우 회색라인에 마우스가 가깝지만 파란라인에 툴팁이 보여질수 있어서 버그처럼 보일 수 있다.
* 좌표계 차트는 `x좌표 우선 탐색` 대신, 데이터의 x y 포지션과 마우스 포인트와의 절대 거리를 중심으로 탐색하는`좌표 거리 탐색` 이 적용되도록 변경하여 해결.
=> feat: tooltip mouse event search for coordinate type chart

src/js/components/mouseEventDetectors/mouseEventDetectorBase.js, src/js/plugins/raphaelLineTypeBase.js, test/plugins/raphaelLineTypeBase.spec.js
라인, 에어리어 차트에서 rerender나 setData api 사용후 zoom 기능 사용시 자바스크립트 에러가 나타나는 경우가 있음.
1. 라인 에어리어 타입 차트의 animate를 위한 clipRect 영역의 x, y 포지션이 한번 생성되면  rerender시에는 업데이트 되지 않는 문제가 있음 
2. rerender 시에 `this.positionMap` left, top 포지션이 갱신되지 않아 이벤트 포지션 계산이 어긋나는 문제가 있음
1. animate를 위한 clipRect 영역의 animate시 항상 x, y 포지션을 새로 세팅해줌.
2. 차트 rerender시 `this.positionMap` 값을 새로운 값으로 갱신해주도록 함
=> fix: event position calculation after `rerender`

CONTRIBUTING.md, README.md
Broken link "Issue guideline" in `README.md` file fix
Change `npm run lint` to `npm run eslint` in `CONTRIBUTING.md` file, because `npm run lint` command doesn't exist, just `npm run eslint` and running previous command reports error to user
=> Docs: broken link and npm script command name fix

index.d.ts, test/types/tsconfig.json
Remove **esModuleInterop**, **allowSyntheticDefaultImports** options in `tsconfig.json`.
Change 'tui-chart' class export type to `default` in `index.d.ts`.
---
=> fix: Change chart export type to default export

index.d.ts
I updated the IThemeConfig interface to use the existing IThemeRange interface for the chart.background option. 
The code was already assuming that the option is of type IThemeRange and not just string and also the docs were showing.
=> Fix: use IThemeRange for chart.background option

src/js/components/axes/axis.js, src/js/helpers/renderUtil.js, src/js/models/boundsAndScaleBuilder.js, src/js/models/scaleData/axisDataMaker.js, src/js/models/scaleData/scaleDataModel.js, test/models/scaleData/axisDataMaker.spec.js
* move YAxis when set rotateLabel false
---
=> fix:move YAxis when set rotateLabel false

src/js/components/mouseEventDetectors/groupTypeEventDetector.js, src/js/components/mouseEventDetectors/mouseEventDetector.js, src/js/components/tooltips/groupTooltip.js
* When using the xAxis `pointOnColumn` and tooltip `grouped` properties at the same time, the tooltip alignment line and point are not aligned as above.
---
=> fix: group tooltip render properly with xAxis pointOnColumn option

src/js/components/legends/spectrumLegend.js, src/js/plugins/raphaelBoxTypeChart.js, src/js/themes/defaultTheme.js
```js
var theme = {
series: {
startColor: '#ffefef',
endColor: '#ac4142',
borderColor: '#fff', // heatmap border color
borderWidth: 2 // heatmap border width
},
legend: {
label: {
color: 'blue' // heatmap / treemap spectrum font color
}
}
};
```
---
=> feat: add heatmap border, spectrum font color options

src/component/boxSeries.ts, src/helpers/series.ts, src/store/dataRange.ts, src/store/seriesData.ts, stories/bar.stories.ts, stories/column.stories.ts, stories/data.ts, tests/helpers/series.spec.ts, types/store/store.d.ts
* feat: render group stack chart
* input  data
```js
const data = {
categories: ['June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
series: [
{
name: 'Budget',
data: [5000, 3000, 5000, 7000, 6000, 4000, 1000],
stackGroup: 'A'
},
{
name: 'Income',
data: [8000, 1000, 7000, 2000, 6000, 3000, 5000],
stackGroup: 'B'
},
{
name: 'Expenses',
data: [4000, 4000, 6000, 3000, 4000, 5000, 7000],
stackGroup: 'A'
},
{
name: 'Debt',
data: [6000, 3000, 3000, 1000, 2000, 4000, 3000],
stackGroup: 'B'
}
]
};
```
* screenshot
| bar | column |
| --- | --- |
| <img width="1029" alt="스크린샷 2020-05-06 14 45 02" src="https://user-images.githubusercontent.com/43128697/81154564-fc705580-8fbe-11ea-9bcd-1d6cc1cbc7d5.png"> | <img width="1035" alt="스크린샷 2020-05-06 14 44 50" …
=> feat: render group stack chart

src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/bubbleChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/lineChart.ts, src/charts/scatterChart.ts, src/store/category.ts, src/store/root.ts, src/store/seriesData.ts, src/store/store.ts, tests/store/category.spec.ts, tests/store/root.spec.ts, tests/store/seriesData.spec.ts, tests/store/store.spec.ts, types/store/store.d.ts
- extract category module.
- some related codes fixed.
- add tcs and modified.
- store module setup interface changed
- Use `modules` property of chart instead.
```typescript
initialize() {
this.store.setModule(module1);
this.store.setModule(module2);
...
}
```
to
```typescript
class barChart extends Chart {
modules = [modules1, modules2]
...
}
```
- we can change whole module setup order (includes default modules) by overriding `Chart.initStore(defaultModules[])`
=> feat: store module setup interface changed and extract category module

src/animator.ts, src/charts/chart.ts, stories/line.stories.ts, types/options.d.ts
```ts
series: {
animation: boolean | { duration: number } 
}
}
```
---
=> feat: set init animation duration by options

src/component/boxPlotSeries.ts, src/component/selectedSeries.ts, src/helpers/responders.ts
* When the event detection type is `grouped`, the previously set inactive color value is set when clicking another model.
| AS-IS | TO-BE |
| --- | --- |
| ![스크린샷 2020-10-19 15 16 05](https://user-images.githubusercontent.com/43128697/96408315-31473080-121e-11eb-8a37-aa5a08abced2.png) | <img width="918" alt="스크린샷 2020-10-19 15 16 25" src="https://user-images.githubusercontent.com/43128697/96408331-36a47b00-121e-11eb-8ed8-82f6dcef1e65.png"> |
* When the event detection type is `point`, If the event detection type is 'point',
Add logic to check if the same model is clicked.
---
=> fix: resolve selected boxPlot series

src/helpers/dataLabels.ts, stories/bar.stack.stories.ts, stories/column.stack.stories.ts, types/components/dataLabels.d.ts, types/options.d.ts
```ts
...
series: {
stack: true,
dataLabels: {
visible: true,
formatter: (value) => `$${value}`,
anchor: 'center',
stackTotal: {
visible: true,
formatter: (value) => `Total $${value}`,
},
},
},
};
```
---
=> feat: add formatter for data labels of stack total

src/js/charts/lineChart.js
`tickInterval: 'auto'` options is not working when `setData` using empty data is entered at the first rendering
---
=> fix: check data and remove options when setData

apps/chart/src/component/legend.ts, apps/chart/src/store/layout.ts, apps/chart/src/store/legend.ts, apps/chart/stories/brush.stories.ts, apps/chart/stories/circleLegend.stories.ts, apps/chart/stories/data.ts, apps/chart/tests/store/layout.spec.ts, apps/chart/tests/store/legend.spec.ts, apps/chart/types/components/legend.d.ts, apps/chart/types/store/store.d.ts
* fix legend item event detection area(#560)
---
=> fix: legend overlap when item text overflows

apps/chart/examples/example01-11-area-chart-responsive.html, apps/chart/examples/example02-08-bar-chart-responsive.html, apps/chart/examples/example03-03-boxPlot-chart-responsive.html, apps/chart/examples/example04-03-bubble-chart-responsive.html, apps/chart/examples/example06-08-column-chart-responsive.html, apps/chart/examples/example07-05-heatmap-chart-responsive.html, apps/chart/examples/example08-10-line-chart-responsive.html, apps/chart/examples/example09-08-pie-chart-responsive.html, apps/chart/examples/example10-05-radar-chart-responsive.html, apps/chart/examples/example11-03-scatter-chart-responsive.html, apps/chart/examples/example12-06-treemap-chart-responsive.html, apps/chart/src/charts/chart.ts, apps/chart/src/message.ts, docs/en/common-api.md, docs/ko/common-api.md
=> fix: infinite height increase with auto options(#551)

apps/chart/src/component/lineSeries.ts, apps/chart/src/component/selectedSeries.ts
=> fix : select series for grouped (fix #565)

apps/chart/src/component/exportMenu.ts, apps/chart/src/component/tooltip.ts, apps/chart/src/css/chart.css, apps/chart/src/helpers/tooltip.ts
=> fix: get chart el top, left position after rendering

apps/chart/src/helpers/style.ts, apps/chart/src/painter.ts
Fix not to show error message continuously
---
=> chore: show canvas unsupported feature warning only once

apps/chart/src/component/tooltip.ts, apps/chart/src/helpers/dom.ts, apps/chart/src/helpers/htmlSanitizer.ts, apps/chart/src/helpers/utils.ts
Fix for Cross-site Scripting vulnerability
Resolves the bug  mentioned in #601 completely without affecting any functionality
Fully described here https://github.com/418sec/tui.chart/pull/2
Please do not merge this commit directly as I said here https://github.com/nhn/tui.chart/issues/601#issuecomment-786454161
Once you are happy with the fix, please comment here https://github.com/418sec/tui.chart/pull/2 🚀. Thanks in advance 😄 
---
=> Security fix for Cross-Site Scripting Vulnerability in the legend fields

apps/chart/src/store/plot.ts, apps/chart/stories/plot.stories.ts
```js
plot: {
bands: [{
range: [3, 8], // not working
range: [[3, 8]], // working
}]
}
}
```
* render bands properly not nested bands data
---
=> fix: render bands properly not nested bands data

apps/chart/.storybook/main.js, apps/chart/src/store/seriesData.ts
* A problem occurs when calculating the x, y coordinates by judging null data with a coordinate chart.
---
=> fix: not to judge null data as coordinate chart

apps/chart/src/charts/chart.ts, apps/chart/src/helpers/coordinate.ts, apps/chart/src/painter.ts
=> fix: add canvas mouseout event

docs/en/common-api.md, docs/ko/common-api.md
I found a typo(`destory`), so I just fixed it(`destroy`)
=> docs: fix typo

apps/chart/src/component/boxSeries.ts, package-lock.json
There is a problem with `dataLabels` on Bar-like charts using `useSeriesColor` option. Even though it sets the option, colors of `dataLabels` aren't changed.
---
=> fix: fix box type data labels using useSeriesColor option

apps/chart/stories/bar.stories.ts
There was a problem with an option for rotatable charts. It doesn't need to `auto` value of sizes with calling `createChart` function.
Edit chart option to fix an error. 
---
=> fix: fix chart option for rotatable story

apps/vue-chart/webpack.config.js
This PR is to fix vue-chart build script. When `@toast-ui/vue-chart` is imported in the version before the change, the chart is contained in an `toastui` object.
* When we write code below
```js 
import tui from '@toast-ui/vue-chart;
console.log(tui);
```
Related to [#686](https://github.com/nhn/tui.chart/issues/686)
---
=> fix: remove library module name in vue wrapper build

apps/chart/src/helpers/axes.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/heatmapAxes.ts, apps/chart/types/store/store.d.ts
* The problem was that the label axis rotation logic didn't consider the chart layout into account.
* From now on, rotate the label by comparing `MaxLabelWidth` to the starting point of `LabelAxis`.
---
=> feat: consider the chart layout in the axis rotation calculation.

apps/chart/src/component/heatmapSeries.ts, apps/chart/src/component/scatterSeries.ts, apps/chart/stories/data.ts, apps/chart/stories/heatmap.stories.ts, apps/chart/stories/scatter.stories.ts, apps/chart/types/index.d.ts
* Fix an error in a TypeScript environment because the `index.d.ts` don't have `selectSeries` and `unselectSeries` types.
* Fix a bug that `selectSeries` with ScatterChart
* Even though call the 'selectSeries', it doesn't highlight the point.
* Fix a bug that `selectSeries` with Heatmap 
* When the user call `selectSeries`, it works like a hover state.
---
=> fix: Add Type for selectSeries, unselectSeries and fix bug releated with selectSeries

apps/chart/src/charts/areaChart.ts, apps/chart/src/charts/columnChart.ts, apps/chart/src/charts/columnLineChart.ts, apps/chart/src/charts/lineAreaChart.ts, apps/chart/src/charts/lineChart.ts, apps/chart/src/charts/lineScatterChart.ts, apps/chart/src/component/component.ts, apps/chart/src/component/rangeSelection.ts, apps/chart/src/store/legend.ts, apps/chart/src/store/seriesData.ts, apps/chart/stories/area.stories.ts, apps/chart/stories/column.stories.ts, apps/chart/stories/line.stories.ts, apps/chart/types/components/rangeSelection.d.ts, apps/chart/types/eventEmitter.d.ts, apps/chart/types/options.d.ts, apps/chart/types/store/store.d.ts
* add `rangeSelection` custom event interface
* ```js
chart.on('rangeSelection', (selectedRange) => {
console.log(selectedRange);
});
```
* ![rangeselection](https://user-images.githubusercontent.com/30035674/201798832-24a9650c-2d84-405d-a3fd-da52c181e537.gif)
---
=> feat: rangeSelection feature on LineType, Column Chart
