nhn/tui.chart

README.md
Revised sentences in the description of the program for clarity and grammar
Removed some fluff words due to redundancy
=> docs: revised description for clarity

README.md
=> chore: add cdn info in readme.md

src/js/components/plots/plot.js, test/components/plots/plot.spec.js
- plotLine animation of the dynamic chart does not work and blotband setting does not work. #81
(다이나믹 차트에 plotLine, plotBands설정시 애니메이션효과가 나타나지 않는 수정)
- http://10.78.9.21:8082/examples/example12-01-dynamic-chart-append-and-shift-data-dynamically.html
=> fix: dynamic chart animation

src/js/components/mouseEventDetectors/boundsBaseCoordinateModel.js, src/js/components/plots/plot.js, src/js/const.js, src/js/plugins/raphaelBarChart.js, test/components/mouseEventDetectors/boundsBaseCoordinateModel.spec.js, test/components/plots/plot.spec.js, test/plugins/raphaelBarChart.spec.js
-   If data is 0, the tooltip is not visible. #73 for versin 2.x.x
- http://localhost:8080/examples/example01-01-bar-chart-basic.html
=> fix: even if data is zero, the tooltip show for version 2.x.x (fix #74)

src/js/helpers/arrayUtil.js, src/js/helpers/calculator.js, src/js/helpers/chartExporter.js, src/js/helpers/colorutil.js, src/js/helpers/consoleUtil.js, src/js/helpers/dataExporter.js, src/js/helpers/domHandler.js, src/js/helpers/downloader.js, src/js/helpers/drawingToolPicker.js, src/js/helpers/eventListener.js, src/js/helpers/geometric.js, src/js/helpers/imageExporter.js, src/js/helpers/objectUtil.js, src/js/helpers/predicate.js, src/js/helpers/renderUtil.js, src/js/helpers/seriesDataImporter.js, src/js/helpers/templateMaker.js, src/js/plugins/pluginRaphael.js, src/js/plugins/raphaelAxisComponent.js, src/js/plugins/raphaelBarChart.js, src/js/plugins/raphaelLegendComponent.js, src/js/plugins/raphaelRenderUtil.js, src/js/plugins/raphaelTitleComponent.js
=> codereview - helpers & plugins1

README.md
=> chore: add message for usedBy and Wrappers

examples/example03-06-line-chart-secondary-axis.html, examples/example08-01-combo-chart-column-and-line.html, src/js/charts/chartBase.js
=> chore: fixed example and add jsdoc event

index.d.ts, package.json, tsBannerGenerator.js
* chore: update automatically version for typescript declaration file
---
=> chore: update automatically version for typescript declaration file

index.d.ts, test/types/comboChart.ts
- 다른 외부 라이브러리(타입스크립트 정의 파일이 포함되어있는)와 사용할 때
타입이 global로 작용하여 같은 type name이 duplicate 된다고 timescript compiler가 에러를 표시한다.
- namespace 안에 정의하여 선언된 것을 독립적으로 사용하도록 수정한다.
---
=> chore : fix global type

examples/example03-01-line-chart-basic.html, package-lock.json, src/js/components/plots/plot.js, test/components/plots/plot.spec.js
아래 이미지와 같이 xAxis.pointOnColumn옵션(라인차트의 좌표가 그려지는 위치가 tick과 tick사이의 가운데로 변경됨)과 함께 plot.lines 옵션을 함께 사용하면 plotLine이 `03/01/2016`의 정확한 위치에 그려지지 않음.
기존의 고려가 안된 xAxis.pointOnColumn 옵션을 고려하여 정확한 포지션을 계산해주도록 변경
=> fix: bug left position addplotline at pointOnColumn

README.md, maps/taiwan.js, maps/thailand.js
remove unnecessary maps parameter(taiwan, thailand) and chnage readme release link
#173
=> fix: remove unnecessary maps parameter(taiwan, thailand) and chnage readme release link

src/less/style.less
=> fix: The tooltip is covered by the export menu

src/js/chart.js, src/js/charts/chartBase.js, src/js/plugins/pluginRaphael.js, src/js/plugins/raphaelLineTypeBase.js, src/js/plugins/raphaelRadialLineSeries.js
#152 radial chart resize error
#163 Resized map chart overflows
#182 radial chart showArea option not working
---
=> Fix: radial chart resize, showArea option and map chart overflow bug 

src/js/components/mouseEventDetectors/areaTypeDataModel.js
=> fix: check empty value when bring left value on zooming

src/js/charts/chartBase.js, src/js/charts/componentManager.js, src/js/charts/lineAreaComboChart.js, src/js/charts/mapChart.js, src/js/charts/mapChartMapModel.js, src/js/components/mouseEventDetectors/areaTypeEventDetector.js, src/js/components/mouseEventDetectors/zoomMixer.js, src/js/components/series/mapChartSeries.js, src/js/models/data/dataProcessor.js, src/js/models/data/dataProcessorBase.js, src/js/models/data/mapChartDataProcessor.js, test/charts/chartBase.spec.js
#164 #188 
fix map chart setData 
---
=> fix: map chart setData (#164)

src/js/components/mouseEventDetectors/zoomMixer.js, src/js/components/plots/plot.js, src/js/helpers/arrayUtil.js, src/js/models/data/dataProcessor.js, test/components/mouseEventDetectors/zoomMixer.spec.js, test/components/plots/plot.spec.js
=> fix: zoom and band issue on coordinate data chart(#190, #192)

src/js/charts/componentManager.js
=> fix: call presetBeforeRerender only zoomable(#191)

README.md
=> chore: apply readme review(#196)

src/js/components/mouseEventDetectors/zoomMixer.js, src/js/models/data/dataProcessor.js
=> fix: filter by value only with line chart with coordinate data

README.md
=> chore: change readme broken link

CODE_OF_CONDUCT.md, CONTRIBUTING.md, bower.json, docs/README.md, docs/wiki/chart-type-radial.md, docs/wiki/chart-types-bar,column.md, docs/wiki/chart-types-bubble.md, docs/wiki/chart-types-column-line-combo.md, docs/wiki/chart-types-heatmap.md, docs/wiki/chart-types-line,area.md, docs/wiki/chart-types-line-area-combo.md, docs/wiki/chart-types-line-scatter-combo.md, docs/wiki/chart-types-map.md, docs/wiki/chart-types-pie-donut-combo.md, docs/wiki/chart-types-pie.md, docs/wiki/chart-types-scatter.md, docs/wiki/chart-types-treemap.md, docs/wiki/features-axes.md, docs/wiki/features-plot.md, docs/wiki/features-series.md, docs/wiki/features-tooltip.md, docs/wiki/table-of-supported-options.md, jsdoc.conf.json, package.json, src/js/models/scaleData/axisDataMaker.js, tuidoc.config.json
=> chore: change org name

src/js/charts/chartBase.js, src/js/components/mouseEventDetectors/mouseEventDetectorBase.js
=> feat: add selectSeriesByIndexes API

index.d.ts, karma.conf.js, package-lock.json, package.json, src/js/chart.js, src/js/components/axes/axis.js, src/js/helpers/renderUtil.js, src/js/models/bounds/axisCalculator.js, src/js/plugins/raphaelRenderUtil.js, test/models/bounds/axisCalculator.spec.js
```js
chart: {
// ..
},
yAxis: {
title: 'Month',
maxWidth: 30
},
xAxis: {
title: 'Amount',
maxWidth: 20
}
};
chart.barChart(container, data, options);
```
---
=> feat: axis label ellipsis

karma.conf.js, package-lock.json, package.json, src/js/chart.js, src/js/components/axes/axis.js, src/js/plugins/raphaelAxisComponent.js
```js
xAxis: {
align: 'right' || 'left' // default 'right'
} 
}
```
---
=> feat: add chart xAxis title align option

index.d.ts
=> chore: rename theme type

index.d.ts, src/js/charts/chartBase.js
* Destroys the chart instance.
```js
var chart = new LineChart({ ... });
chart.destroy();
```
---
=> feat: destroy api

index.d.ts, src/js/charts/chartBase.js, src/js/charts/componentManager.js, src/js/components/series/lineTypeSeriesBase.js, src/js/components/series/series.js, src/js/plugins/raphaelAreaChart.js, src/js/plugins/raphaelBarChart.js, src/js/plugins/raphaelBoxplotChart.js, src/js/plugins/raphaelBulletChart.js, src/js/plugins/raphaelCoordinateTypeChart.js, src/js/plugins/raphaelLineChart.js, src/js/plugins/raphaelLineTypeBase.js, src/js/plugins/raphaelPieChart.js, src/js/plugins/raphaelRenderUtil.js, test/charts/barChart.spec.js, test/charts/chartBase.spec.js, test/charts/lineChart.spec.js
* add series animation duration options
* Apply only at initial render
```js
series: {
animation: false
}
}
// or
series: {
animation: {
duration: 0 // number
}
}
}
```
* except `radial`, `map`, `box`, `dynamically line` type chart
* add `animation` parameter to `setData`
* default: `true`
```js
chart.setData(rawData, false); // off animation
chart.setData(rawData, {duration: 1000}); // set animation duration 
```
---
=> feat: change animation policy

package-lock.json, package.json
=> chore: dependency version update

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, src/js/components/mouseEventDetectors/areaTypeDataModel.js, src/js/components/mouseEventDetectors/areaTypeEventDetector.js, src/js/const.js, src/less/style.less
=> fix: improving tooltip 

src/js/chart.js
* add pointOnColumn to columnChart
* fix pointOnColumn type (number -> boolean)
---
=> chore: fix type

src/js/components/mouseEventDetectors/areaTypeDataModel.js, src/js/components/mouseEventDetectors/areaTypeEventDetector.js, src/js/components/series/lineTypeSeriesBase.js, src/js/models/data/dataProcessor.js
=> fix: line scatter combo event detecting

.browserslistrc, .eslintrc.js, package.json, stories/index.stories.ts, tsconfig.json, webpack.config.js
* change package.json property
* change config options
---
=> chore: apply new options

docs/COMMIT_MESSAGE_CONVENTION.md, src/js/components/tooltips/groupTooltip.js
#260 
* add missing setting
---
=> fix: add missing setting tickinterval on tooltip(#260)

src/js/components/mouseEventDetectors/groupTypeEventDetector.js
* hide group tooltip line after zoom and reset
---
=> fix: hide group tooltip line after zoom

package.json, src/brushes/lineSeries.ts, src/brushes/tooltip.ts, src/charts/chart.ts, src/charts/lineChart.ts, src/component/lineSeries.ts, src/component/tooltip.ts, src/helpers/utils.ts, src/painter.ts, src/store/axes.ts, src/store/dataRange.ts, src/store/reactive.ts, src/store/seriesData.ts, src/store/store.ts, tests/store/reactive.spec.ts, tests/store/store.spec.ts, types/components/tooltip.d.ts, types/options.d.ts, types/store/store.d.ts
* apply tooltip style
* divide series state and options
---
=> refactor: dot tooltip style

src/js/components/tooltips/groupTooltip.js, test/components/tooltips/groupTooltip.spec.js
* only `column` and `area` chart
* change tooltip order
---
=> fix: change grouped tooltip order when using tooltip

.babelrc, package-lock.json, src/helpers/calculator.ts, src/helpers/utils.ts, src/painter.ts
* chore: add `.babelrc` file
* chore: change npm repo name(@toast-ui/chart)
* fix: resolve anti-aliasing for font
* fix: adjust crisp pixel for drawing line on canvas
---
=> Improvement : resolve antialiasing and adjust crisp pixel on canvas

.eslintrc.js, src/component/boxSeries.ts, src/helpers/utils.ts, src/store/dataRange.ts, src/store/store.ts, stories/bar.stories.ts, stories/column.stories.ts, stories/data.ts, tests/helpers/utils.spec.js, tests/helpers/utils.spec.ts, types/options.d.ts
Feat : Create box chart for using **Range Data**
- Bar 
- Column
---
=> Feat : Create box chart for using range data

src/js/components/legends/legend.js, src/js/plugins/raphaelLegendComponent.js, test/components/legends/legend.spec.js
* https://nhnent.dooray.com/project/posts/2727508615234757598
---
=> fix: remove legend pagination when rerender

src/js/charts/chartBase.js
* tickInterval = 'auto' is not working with setData
---
=> fix: reset prevXData when calling setData

src/store/reactive.ts, src/store/store.ts, types/store/store.d.ts
* use deep copied store state
---
=> fix: use deep copied data

jest.config.js, src/charts/areaChart.ts, src/charts/lineChart.ts, src/charts/scatterChart.ts, src/component/areaSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/lineSeries.ts, src/component/scatterSeries.ts, src/store/axes.ts, stories/area.stories.ts, stories/line.stories.ts, tests/components/areaSeries.spec.ts, tests/components/boxSeries.spec.ts, tests/components/boxStackSeries.spec.ts, types/options.d.ts, types/store/store.d.ts
=> feat: pointOnColumn options

src/brushes/basic.ts, src/brushes/boxSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, stories/bar.stories.ts, stories/brush.stories.ts, stories/column.stories.ts, types/components/axis.d.ts, types/components/series.d.ts, types/store/store.d.ts
* create stack series with connector
| default(solid type) | set `dashed type, color, width`|
| --- | --- |
| <img width="1042" alt="스크린샷 2020-05-14 21 22 18" src="https://user-images.githubusercontent.com/43128697/81934006-31b51d00-9629-11ea-8e31-1af9f7c826fd.png"> | <img width="825" alt="스크린샷 2020-05-14 21 22 58" src="https://user-images.githubusercontent.com/43128697/81933998-2cf06900-9629-11ea-98d2-188b8dfeaab3.png"> |
---
=> feat: render stack with connector

src/store/axes.ts, src/store/dataRange.ts, src/store/layout.ts, src/store/scale.ts, src/store/seriesData.ts, src/store/stackSeriesData.ts, src/store/store.ts, tests/store/axes.spec.ts, tests/store/stackSeriesData.spec.ts, types/store/store.d.ts
* divide extend func
* add store test
---
=> feat: store/extend

src/charts/barChart.ts, src/charts/columnChart.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/plot.ts, src/helpers/axes.ts, src/helpers/utils.ts, src/store/axes.ts, src/store/dataRange.ts, src/store/plot.ts, src/store/store.ts, stories/bar.stories.ts, stories/column.stories.ts, stories/data.ts, tests/components/boxSeries.spec.ts, tests/components/boxStackSeries.spec.ts, tests/helpers/utils.spec.ts, tests/store/plot.spec.ts, tests/store/stackSeriesData.spec.ts, types/options.d.ts, types/store/store.d.ts
- [x[ It's submitted to right branch according to our branching model
* Rendering the negative values ​​in the box series
* Rendering the diverging data in the box series
* Refactoring to calibrate box rendering coordinates and size
| | bar | column |
| --- | --- | --- |
| negative | <img width="812" alt="스크린샷 2020-05-21 10 58 27" src="https://user-images.githubusercontent.com/43128697/82514967-09aa4a00-9b52-11ea-8e0e-8e8da8f85e12.png"> | <img width="817" alt="스크린샷 2020-05-21 10 58 05" src="https://user-images.githubusercontent.com/43128697/82514983-10d15800-9b52-11ea-892b-4e359fbe04d5.png">|
| diverging | <img width="814" alt="스크린샷 2020-05-21 10 58 33" src="https://user-images.githubusercontent.com/43128697/82514993-162ea280-9b52-11ea-91b0-2b3f33a7f5ba.png"> | <img …
=> Feat : render negative and basic diverging on Box Series

src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/scale/coordinateScaleCalculator.ts, src/store/dataRange.ts, src/store/scale.ts, src/store/store.ts, stories/bar.stories.ts, stories/line.stories.ts, stories/scatter.stories.ts, tests/store/scale.spec.ts, types/options.d.ts, types/store/store.d.ts
=> feat: options/min-max

src/helpers/calculator.ts, src/scale/coordinateScaleCalculator.ts, src/store/axes.ts, stories/line.stories.ts, tests/store/axes.spec.ts, tests/store/plot.spec.ts, tests/store/scale.spec.ts, types/store/store.d.ts
=> feat: step size

src/component/scatterSeries.ts, src/helpers/axes.ts, src/helpers/coordinate.ts, src/store/axes.ts, src/store/dataRange.ts, src/store/scale.ts, stories/line.stories.ts, stories/scatter.stories.ts, tests/store/scale.spec.ts, types/store/store.d.ts
* apply scale options to coordinate chart
---
=> Feat: scatter/overflow

src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/component.ts, src/component/componentManager.ts, src/helpers/color.ts, src/helpers/range.ts, tests/components/boxSeries.spec.ts
* Improves animation of boxSeries
---
=> Improvement : box series animation

src/brushes/basic.ts, src/charts/bubbleChart.ts, src/component/areaSeries.ts, src/component/bubbleSeries.ts, src/component/circleSeries.ts, src/component/lineSeries.ts, src/component/scatterSeries.ts, src/helpers/calculator.ts, src/helpers/coordinate.ts, stories/bubble.stories.ts, stories/data.ts, tests/components/bubbleSeries.spec.ts, types/components/series.d.ts, types/options.d.ts, types/store/store.d.ts
=> Feat: bubble/basic

src/store/axes.ts, tests/store/axes.spec.ts
Make interval datas using state function not initialize.
=> fix: axes store uses state function not initialize

src/brushes/tooltip.ts, src/component/bubbleSeries.ts, src/component/circleSeries.ts, src/component/scatterSeries.ts, src/helpers/calculator.ts, stories/brush.stories.ts, tests/components/bubbleSeries.spec.ts, tests/components/scatterSeries.spec.ts, types/components/tooltip.d.ts, types/options.d.ts
* circle tooltip
1. near the center of the circle
2. Select when the circle radius is small when the distance is close
---
=> Feat: circle/tooltip

src/charts/barChart.ts, src/charts/chart.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/helpers/axes.ts, src/helpers/coordinate.ts, src/store/axes.ts, src/store/root.ts, src/store/seriesData.ts, src/store/stackSeriesData.ts, src/store/store.ts, tests/store/axes.spec.ts, tests/store/stackSeriesData.spec.ts, tests/store/store.spec.ts, types/options.d.ts, types/store/store.d.ts
- Store initialize is removed and make it same functionalty within state function
- Extract root store module fron store.ts
- SeriesState type is removed and replaced to Series
- Related module & tcs updated
=> refactor: remove initialize for state function and seriesData store module enhanced

src/animator.ts, src/charts/areaChart.ts, src/charts/chart.ts, src/component/areaSeries.ts, src/component/circleSeries.ts, src/component/component.ts, src/component/lineSeries.ts, src/store/reactive.ts, tests/components/areaSeries.spec.ts
=> feat: series animation

src/brushes/circleLegend.ts, src/charts/bubbleChart.ts, src/charts/chart.ts, src/component/bubbleSeries.ts, src/component/circleLegend.ts, src/component/component.ts, src/painter.ts, src/scale/coordinateScaleCalculator.ts, src/store/layout.ts, stories/brush.stories.ts, stories/bubble.stories.ts, tests/components/bubbleSeries.spec.ts, tests/components/circleLegend.spec.ts, types/components/circleLegend.d.ts, types/options.d.ts, types/store/store.d.ts
* add legend options
```ts
circleLegend: {
visible: false,
},
};
```
---
=> feat: bubble/circle legend

src/brushes/basic.ts, src/brushes/legend.ts, src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/bubbleChart.ts, src/charts/columnChart.ts, src/charts/lineChart.ts, src/charts/scatterChart.ts, src/component/axis.ts, src/component/axisTitle.ts, src/component/component.ts, src/component/title.ts, src/store/axes.ts, src/store/layout.ts, stories/area.stories.ts, stories/bar.stories.ts, stories/bubble.stories.ts, stories/column.stories.ts, stories/line.stories.ts, stories/scatter.stories.ts, tests/components/axisTitle.spec.ts, tests/components/title.spec.ts, types/options.d.ts, types/store/store.d.ts
=> Feat: common/title

__mocks__/styleMock.ts, jest.config.js, src/brushes/exportMenu.ts, src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/bubbleChart.ts, src/charts/columnChart.ts, src/charts/lineChart.ts, src/charts/scatterChart.ts, src/component/component.ts, src/component/exportMenu.ts, src/css/exportMenu.css, src/helpers/downloader.ts, src/painter.ts, src/responderDetectors.ts, src/store/layout.ts, stories/brush.stories.ts, types/components/exportMenu.d.ts, types/options.d.ts, types/store/store.d.ts
* options
```js
exportMenu: {
visible: boolean;
filename: string;
}
};
```
* close 
* open
---
=> Feat: common/export menu

src/component/axis.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/helpers/axes.ts, src/store/stackSeriesData.ts, tests/components/boxSeries.spec.ts, tests/components/boxStackSeries.spec.ts, types/components/series.d.ts
* disable/enable series
* active/inactive series
---
=> Fix : specify color on stack series

src/store/axes.ts
=> fix: add zeroPosition prop if needed

src/component/areaSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/bubbleSeries.ts, src/component/component.ts, src/component/lineSeries.ts, src/component/scatterSeries.ts, src/helpers/legend.ts, tests/components/areaSeries.spec.ts, types/components/series.d.ts
=> Fix: add active series map 

src/component/areaSeries.ts, src/component/lineSeries.ts, stories/area.stories.ts, stories/line.stories.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, types/components/series.d.ts
=> feat: add show dot options with test

src/component/areaSeries.ts, src/component/boxSeries.ts, src/component/component.ts, src/component/exportMenu.ts, src/component/legend.ts, src/component/zoom.ts, src/helpers/range.ts, src/responderDetectors.ts, src/store/dataLabels.ts, tests/components/areaSeries.spec.ts, types/components/legend.d.ts, types/components/series.d.ts
* remove label, bound, checkbox responder
* use 'rect' responder model
---
=> refactor: change responder

src/component/areaSeries.ts, src/component/dataLabels.ts, src/component/hoveredSeries.ts, src/component/zoom.ts, src/helpers/coordinate.ts, src/store/reactive.ts, src/store/seriesData.ts, tests/components/areaSeries.spec.ts, tests/store/seriesData.spec.ts
=> chore: filter datalabel, line points model using rect

src/brushes/sector.ts, src/component/pieSeries.ts, src/helpers/sector.ts, src/store/dataLabels.ts, stories/brush.stories.ts, stories/pie.stories.ts, tests/components/pieSeries.spec.ts, types/components/series.d.ts, types/options.d.ts
* render pie series for donut shape
| center series name |
| --- |
| <img width="655" alt="스크린샷 2020-07-29 11 19 59" src="https://user-images.githubusercontent.com/43128697/88749184-b8d85280-d18d-11ea-9d9a-2b9aec15429a.png"> |
| outer series name |
| --- |
| <img width="658" alt="스크린샷 2020-07-29 11 20 30" src="https://user-images.githubusercontent.com/43128697/88749194-c097f700-d18d-11ea-856e-d47ef2010610.png"> |
---
=> feat: render donut shaped pie chart

src/brushes/tooltip.ts, src/component/bubbleSeries.ts, src/component/scatterSeries.ts, src/component/zoom.ts, src/helpers/calculator.ts, src/helpers/coordinate.ts, src/helpers/formatDate.ts, src/helpers/utils.ts, src/scale/coordinateScaleCalculator.ts, src/scale/datetimeScaleCalculator.ts, src/store/axes.ts, src/store/category.ts, src/store/dataRange.ts, src/store/scale.ts, src/store/seriesData.ts, stories/bubble.stories.ts, stories/data.ts, stories/line.stories.ts, stories/scatter.stories.ts, tests/helpers/formatDate.spec.ts, tests/helpers/utils.spec.ts, tests/store/axes.spec.ts, tests/store/dataRange.spec.ts, types/components/tooltip.d.ts, types/options.d.ts
=> feat: datetype category, datetype coordinate

src/component/bubbleSeries.ts, tests/components/bubbleSeries.spec.ts
* add label to tooltip
* add minimum radius(0.5)
---
=> feat: add label to tooltip, add minimum radius

src/component/bubbleSeries.ts, src/component/circleSeries.ts, src/component/component.ts, src/component/scatterSeries.ts, stories/bubble.stories.ts, stories/scatter.stories.ts, tests/components/bubbleSeries.spec.ts, tests/components/scatterSeries.spec.ts, types/components/series.d.ts, types/options.d.ts
* option
```js
series: {
selectable: boolean
}
}
```
---
=> feat: add selectable option

src/component/areaSeries.ts, src/component/bubbleSeries.ts, src/component/component.ts, src/component/lineSeries.ts, src/component/scatterSeries.ts, stories/area.stories.ts, stories/line.stories.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, types/components/series.d.ts
=> feat: add selectable series to line, area chart

src/component/areaSeries.ts, src/component/lineSeries.ts, stories/area.stories.ts, stories/line.stories.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, types/options.d.ts
* only `line`, `area` chart
```ts
series: {
lineWidth: number;
}
}
```
---
=> feat: add line width options

src/component/areaSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/bubbleSeries.ts, src/component/component.ts, src/component/dataLabels.ts, src/component/lineSeries.ts, src/component/scatterSeries.ts, src/helpers/arrayUtil.ts, src/helpers/utils.ts, src/store/axes.ts, src/store/category.ts, src/store/dataLabels.ts, src/store/dataRange.ts, src/store/seriesData.ts, tests/components/boxSeries.spec.ts, tests/components/boxStackSeries.spec.ts, tests/components/bubbleSeries.spec.ts, tests/components/dataLabels.spec.ts, tests/components/lineSeries.spec.ts, tests/components/scatterSeries.spec.ts, tests/store/dataRange.spec.ts, types/components/dataLabels.d.ts, types/components/series.d.ts
=> Feat: animation upgrade

src/component/tooltip.ts, stories/line.stories.ts, types/components/tooltip.d.ts, types/options.d.ts
```ts
tooltip: {
offsetX: number,
offsetY: number
}
}
```
---
=> feat: change tooltip position according to offset

src/component/areaSeries.ts, stories/area.stories.ts, tests/components/areaSeries.spec.ts
=> feat: add spline area chart

src/brushes/exportMenu.ts, src/brushes/resetButton.ts, src/charts/areaChart.ts, src/charts/lineChart.ts, src/component/areaSeries.ts, src/component/component.ts, src/component/resetButton.ts, src/component/zoom.ts, src/helpers/range.ts, src/store/axes.ts, src/store/layout.ts, src/store/seriesData.ts, tests/store/layout.spec.ts, types/components/resetButton.d.ts, types/components/zoom.d.ts, types/store/store.d.ts
=> refactor: componentization of reset button

src/brushes/resetButton.ts, src/charts/treemapChart.ts, src/component/backButton.ts, src/component/component.ts, src/component/treemapSeries.ts, src/helpers/range.ts, src/store/seriesData.ts, src/store/treemapScale.ts, src/store/treemapSeriesData.ts, stories/brush.stories.ts, stories/treemap.stories.ts, tests/components/treemapSeries.spec.ts, tests/store/treemapSeriesData.spec.ts, types/components/resetButton.d.ts, types/store/store.d.ts
=> Feat: treemap/zoom

src/brushes/basic.ts, src/component/areaSeries.ts, src/component/lineSeries.ts, src/component/radarSeries.ts, src/component/selectedSeries.ts, stories/area.stories.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, tests/components/radarSeries.spec.ts, types/components/series.d.ts
*basic*
*selectable*
*basic*
*selectable*
---
=> refactor: line area style

src/charts/columnLineChart.ts, src/charts/lineAreaChart.ts, src/charts/lineScatterChart.ts, src/component/NestedPieSeries.ts, src/component/boxPlotSeries.ts, src/component/boxSeries.ts, src/component/bulletSeries.ts, src/component/component.ts, src/component/hoveredSeries.ts, src/component/pieSeries.ts, src/component/radarSeries.ts, src/component/selectedSeries.ts, src/helpers/pieSeries.ts, src/helpers/responders.ts, stories/bar.stories.ts, stories/column.stories.ts, stories/nestedPie.stories.ts, tests/components/NestedPieSeries.spec.ts, tests/components/bulletSeries.spec.ts, types/components/tooltip.d.ts
*box*
*boxplot*
*bubble*
*bullet*
*line-scatter*
*nested pie*
*pie*
*radar*
*scatter*
---
=> feat: selectable active

src/component/selectedSeries.ts
* fix: resolve selected pie series
---
=> fix: resolve selected pie series

src/charts/treemapChart.ts, src/component/backButton.ts, src/component/selectedSeries.ts, src/component/treemapSeries.ts, src/eventEmitter.ts, src/helpers/responders.ts, stories/treemap.stories.ts
=> feat: add treemap selectable

src/brushes/basic.ts, src/brushes/lineSeries.ts, src/component/areaSeries.ts, src/component/lineSeries.ts, src/component/radarSeries.ts, src/helpers/theme.ts, src/store/theme.ts, stories/area.stories.ts, stories/line.stories.ts, stories/lineArea.stories.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, tests/store/theme.spec.ts, types/components/series.d.ts, types/options.d.ts, types/theme.d.ts
```ts
interface DotTheme {
radius?: number;
borderColor?: string;
borderWidth?: number;
}
interface theme {
series: {
colors?: string[];
dot?: DotTheme;
select?: {
dot?: DotTheme;
areaOpacity?: number; // selected series area opacity, 🌝  only area chart
restSeries?: {
areaOpacity?: number; // unselected series area opacity, 🌝 only area chart
}
}
hover?: {
dot?: DotTheme;
}
}
};
```
**line**
**area**
**line area**
---
=> feat: line area series theme

src/brushes/dataLabel.ts, src/brushes/label.ts, src/component/dataLabels.ts, src/component/legend.ts, src/component/pieSeries.ts, src/component/selectedSeries.ts, src/helpers/dataLabels.ts, src/helpers/pieSeries.ts, src/helpers/sector.ts, src/helpers/tooltipTemplate.ts, stories/pie.stories.ts, tests/components/pieSeries.spec.ts, types/components/dataLabels.d.ts, types/options.d.ts
```ts
dataLabels: {
visible: true,
anchor: 'outer',
pieSeriesName: {
visible: true,
anchor: 'outer',
},
},
```
---
=> refactor: apply pie new styles

src/charts/heatmapChart.ts, src/component/heatmapSeries.ts, src/component/treemapSeries.ts, src/helpers/responders.ts, src/helpers/theme.ts, src/store/treemapSeriesData.ts, stories/heatmap.stories.ts, stories/treemap.stories.ts, tests/components/heatmapSeries.spec.ts, types/options.d.ts, types/theme.d.ts
```ts
interface TreemapChartSeriesTheme {
colors?: string[];
startColor?: string;
endColor?: string;
border?: BorderTheme;
select?: {
border?: BorderTheme;
};
hover?: {
border?: BorderTheme;
};
}
```
---
=> feat: treemap, heatmap series theme

src/brushes/legend.ts, src/component/legend.ts, src/helpers/theme.ts, src/store/layout.ts, src/store/legend.ts, stories/theme.stories.ts, tests/store/layout.spec.ts, tests/store/theme.spec.ts, types/components/legend.d.ts, types/theme.d.ts
```ts
type FontTheme = {
fontSize?: number;
fontFamily?: string;
fontWeight?: string | number;
};
type LegendTheme = {
label?: FontTheme;
};
```
---
=> feat: legend label theme

src/component/tooltip.ts, src/css/tooltip.css, src/helpers/theme.ts, src/helpers/tooltipTemplate.ts, stories/theme.stories.ts, tests/store/theme.spec.ts, types/options.d.ts, types/theme.d.ts
```ts
type FontTheme = {
fontSize?: number;
fontFamily?: string;
fontWeight?: string | number;
};
type TooltipTheme = {
background?: string;
borderColor?: string;
borderWidth?: number;
borderRadius?: number;
header?: FontTheme;
body?: FontTheme;
};
```
---
=> feat: tooltip theme

src/brushes/axis.ts, src/brushes/label.ts, src/brushes/legend.ts, src/component/axis.ts, src/component/axisTitle.ts, src/component/legend.ts, src/component/title.ts, src/component/tooltip.ts, src/css/tooltip.css, src/helpers/axes.ts, src/helpers/style.ts, src/helpers/theme.ts, src/helpers/tooltipTemplate.ts, src/store/layout.ts, src/store/legend.ts, src/store/theme.ts, stories/brush.stories.ts, stories/theme.stories.ts, tests/components/axes.spec.ts, tests/components/axisTitle.spec.ts, tests/components/title.spec.ts, tests/store/layout.spec.ts, tests/store/theme.spec.ts, types/components/axis.d.ts, types/components/legend.d.ts, types/options.d.ts, types/theme.d.ts
```ts
type FontTheme = {
fontWeight: number | string;
color: string;
fontFamily: string;
fontSize: number;
}
interface theme {
title: FontTheme;
}
```
```ts
interface AxisTheme {
title?: FontTheme;
label?: FontTheme;
width?: number;
}
```
---
=> feat: title, axis theme

src/brushes/basic.ts, src/charts/barChart.ts, src/charts/columnChart.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/pieSeries.ts, src/helpers/theme.ts, src/helpers/utils.ts, src/store/stackSeriesData.ts, stories/bar.groupstack.stories.ts, stories/bar.stack.stories.ts, stories/bar.stories.ts, stories/column.groupstack.stories.ts, stories/column.stack.stories.ts, stories/column.stories.ts, tests/components/boxSeries.spec.ts, tests/components/boxStackSeries.spec.ts, tests/store/scale.spec.ts, tests/store/stackSeriesData.spec.ts, types/options.d.ts, types/store/store.d.ts, types/theme.d.ts
* apply theme options for bar, column series
```ts
type GroupedRect = {
opacity?: number;
};
type ConnectorTheme = {
lineWidth?: number;
dashSegments?: number[];
};
interface BoxChartSeriesTheme extends CommonSeriesTheme {
colors?: string[];
barWidth?: string | number;
areaOpacity?: number;
hover?: {
borderColor?: string;
borderWidth?: number;
groupedRect?: GroupedRect;
shadow?: boolean | ShadowStyle;
} & ShadowStyle;
select?: {
borderColor?: string;
borderWidth?: number;
groupedRect?: GroupedRect;
restSeries?: {
areaOpacity?: number;
};
areaOpacity?: number;
} & ShadowStyle;
connector?: ConnectorTheme;
}
type ShadowStyle = {
shadowColor?: string;
shadowOffsetX?: number;
shadowOffsetY?: number;
shadowBlur?: number;
};
```
--- …
=> feat: apply theme options for bar and column series

src/charts/chart.ts
=> fix: observe painter setup

src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/boxPlotChart.ts, src/charts/bubbleChart.ts, src/charts/bulletChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/lineScatterChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/radarChart.ts, src/charts/scatterChart.ts, src/charts/treemapChart.ts, src/store/category.ts, src/store/legend.ts, src/store/seriesData.ts, src/store/theme.ts, types/options.d.ts
* basic
```js
chart.addSeries(data);
```
* heatmap
```js
chart.addSeries(data, {category});
```
* combo chart
```js
chart.addSeries(data, {category, chartType});
```
---
=> feat: addSeries

src/charts/chart.ts, src/component/legend.ts, src/component/spectrumLegend.ts, src/store/legend.ts, src/store/nestedPieSeriesData.ts, src/store/options.ts, src/store/seriesData.ts, src/store/theme.ts, tests/store/nestedPieSeriesData.spec.ts, tests/store/seriesData.spec.ts, types/index.d.ts, types/store/store.d.ts
```js
chart.setOptions({
chart: {
// ...
},
theme: {
// ...
}
});
```
---
=> feat: setOptions API

src/charts/chart.ts, src/component/hoveredSeries.ts, src/component/resetButton.ts, src/component/selectedSeries.ts, src/component/zoom.ts, src/eventEmitter.ts, types/index.d.ts
```ts
export type CustomEventType =
| 'clickLegendLabel'
| 'clickLegendCheckbox'
| 'selectSeries'
| 'unselectSeries'
| 'hoverSeries'
| 'unhoverSeries'
| 'zoom'
| 'resetZoom';
chart.on('clickLegendLabel', (info) => {
console.log(info);
});
```
---
=> feat: add custom event

src/store/legend.ts
=> fix: add condition for heatmap chart

src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/boxPlotChart.ts, src/charts/bubbleChart.ts, src/charts/bulletChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/lineScatterChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/radarChart.ts, src/charts/scatterChart.ts, src/charts/treemapChart.ts, src/component/component.ts, src/component/componentManager.ts, src/store/heatmapSeriesData.ts, src/store/nestedPieSeriesData.ts, src/store/seriesData.ts, src/store/treemapSeriesData.ts, types/options.d.ts
```js
chart.setData(data);
```
---
=> feat: setData API

src/charts/barChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/component/areaSeries.ts, src/component/boxPlotSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/bubbleSeries.ts, src/component/bulletSeries.ts, src/component/circleLegend.ts, src/component/heatmapSeries.ts, src/component/lineSeries.ts, src/component/pieSeries.ts, src/component/radarSeries.ts, src/component/scatterSeries.ts, src/component/treemapSeries.ts, src/message.ts, src/painter.ts, src/store/reactive.ts, stories/boxPlot.stories.ts
* line, area, bar, column, boxPlot, radar, scatter, bubble, heatmap
```ts
chart.selectSeries({
index: number;
seriesIndex: number;
});
```
* pie, treemap, bullet
```ts
chart.selectSeries({
index: number;
});
```
* line-area, line-scatter, column-line
```ts
chart.selectSeries({
seriesIndex: number;
index: number;
chartType: 'line' | 'area' | 'column' | 'scatter'
});
```
* nestedPie
```ts
chart.selectSeries({
index: number;
alias: string;
});
```
```ts
chart.unselectSeries();
```
---
=> feat: selectSeries, unselectSeries

src/charts/chart.ts, src/store/options.ts, src/store/theme.ts, types/index.d.ts
```ts
chart.resize({
width: number;
});
chart.resize({
height: number;
});
chart.resize({
width: number;
height: number;
});
```
---
=> feat: resize api

src/charts/areaChart.ts, src/charts/columnLineChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/component/plot.ts, src/store/options.ts, src/store/plot.ts, types/index.d.ts, types/options.d.ts, types/store/store.d.ts
* only for area, line, linearea, columnline
```js
chart.addPlotLine(data: PlotLine): void;
chart.removePlotLine(id: string): void;
chart.addPlotBand(data: PlotBand): void;
chart.removePlotBand(id: string): void;
```
---
=> feat: plot api

src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/treemapChart.ts, src/component/dataLabels.ts, src/helpers/dataLabels.ts, src/helpers/pieSeries.ts, types/index.d.ts, types/options.d.ts, types/store/store.d.ts
```js
chart.hideSeriesLabel();
chart.showSeriesLabel();
```
* only for 
* area
* bar
* bullet
* column
* column-line
* heatmap
* line-area
* line
* pie
* nestedPie
* treemap
---
=> feat: show series labels API

src/charts/chart.ts, types/index.d.ts
```js
chart.getOptions();
```
---
=> feat: getOptions API

src/charts/chart.ts, types/index.d.ts
```
chart.setTooltipOffset({x, y});
```
---
=> feat: settooltipoffset api

src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/boxPlotChart.ts, src/charts/bubbleChart.ts, src/charts/bulletChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/lineScatterChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/radarChart.ts, src/charts/scatterChart.ts, src/charts/treemapChart.ts, src/component/component.ts, src/store/axes.ts, src/store/options.ts, types/index.d.ts
```
chart.setOptions(options);
chart.updateOptions(options);
```
---
=> Feat: setOptions / updateOptions

package.json
=> chore: add script for storybook build

src/store/legend.ts, stories/heatmap.stories.ts
| AS-IS | 
| --- | 
| <img width="911" alt="스크린샷 2020-12-08 16 28 13" src="https://user-images.githubusercontent.com/43128697/101453313-80822580-3972-11eb-99f5-114c3bb0d0fc.png"> |
| TO-BE |
| --- |
| <img width="909" alt="스크린샷 2020-12-08 16 27 48" src="https://user-images.githubusercontent.com/43128697/101453354-8d067e00-3972-11eb-852d-b4879118f2db.png"> |
---
=> fix: resolve spectrum legend width default value

package-lock.json, package.json, src/charts/boxPlotChart.ts, src/index.ts, src/store/legend.ts, tsconfig.esm.json, types/index.d.ts, webpack.config.js
=> chore: change build options for alpha release

stories/area.stories.ts, stories/nestedPie.stories.ts, types/index.d.ts, types/options.d.ts
=> refactor: check types

stories/brush.stories.ts, stories/columnLine.stories.ts, stories/nestedPie.stories.ts
=> chore: remove bug story

src/helpers/calculator.ts
=> fix : revert ctx text calulator

src/component/exportMenu.ts, src/helpers/downloader.ts
=> feat: generate exported data by series

.gitignore, README.md, examples/example01-01-bar-chart-basic.html, package.json, src/charts/chart.ts, src/charts/lineChart.ts, tuidoc.config.json
=> feat: tui doc

docs/ko/common-api.md, src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/boxPlotChart.ts, src/charts/bubbleChart.ts, src/charts/bulletChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/lineScatterChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/radarChart.ts, src/charts/scatterChart.ts, src/charts/treemapChart.ts, src/component/pieSeries.ts, src/helpers/downloader.ts, tuidoc.config.json, types/index.d.ts, types/options.d.ts
=> docs: comment for tuidoc

src/store/legend.ts
=> fix: apply legend icon type

src/component/dataLabels.ts, src/helpers/dataLabels.ts
=> fix: check area before add offset

src/helpers/color.ts, tests/helpers/color.spec.ts
=> fix: enable 3-digit hex value rgb convert

docs/ko/common-api.md, src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/bulletChart.ts, src/charts/chart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/treemapChart.ts, src/store/plot.ts, types/index.d.ts
to showSeriesDataLabe, hideSeriesDataLabel
* change method name
`showSeriesLabel()` -> `showSeriesDataLabel()`
`hideSeriesLabel()` -> `hideSeriesDataLabel()`
---
=> refactor: change showSeriesLabel, hideSeriesLabel method name

docs/ko/common-legend.md, src/charts/areaChart.ts, src/charts/barChart.ts, src/charts/boxPlotChart.ts, src/charts/bubbleChart.ts, src/charts/bulletChart.ts, src/charts/columnChart.ts, src/charts/columnLineChart.ts, src/charts/heatmapChart.ts, src/charts/lineAreaChart.ts, src/charts/lineChart.ts, src/charts/lineScatterChart.ts, src/charts/nestedPieChart.ts, src/charts/pieChart.ts, src/charts/radarChart.ts, src/charts/scatterChart.ts, src/charts/treemapChart.ts, types/options.d.ts
=> chore: remove maxwidth options

src/store/layout.ts
=> fix: Use the Rect of the created button

src/component/axis.ts, src/component/plot.ts, src/helpers/axes.ts, src/helpers/calculator.ts, src/helpers/coordinate.ts, src/store/axes.ts, src/store/scale.ts, stories/line.stories.ts, tests/components/axes.spec.ts, tests/store/axes.spec.ts
=> feat: x axis step size auto

src/component/areaSeries.ts, src/component/boxSeries.ts, src/component/boxStackSeries.ts, src/component/lineSeries.ts, src/helpers/responders.ts, tests/components/areaSeries.spec.ts, tests/components/lineSeries.spec.ts, types/components/tooltip.d.ts
=> fix: coordinate nearest detect

src/component/boxStackSeries.ts
=> fix: resolve start position for group stack

apps/chart/src/charts/areaChart.ts, apps/chart/src/charts/barChart.ts, apps/chart/src/charts/boxPlotChart.ts, apps/chart/src/charts/bubbleChart.ts, apps/chart/src/charts/bulletChart.ts, apps/chart/src/charts/columnChart.ts, apps/chart/src/charts/columnLineChart.ts, apps/chart/src/charts/heatmapChart.ts, apps/chart/src/charts/lineAreaChart.ts, apps/chart/src/charts/lineChart.ts, apps/chart/src/charts/lineScatterChart.ts, apps/chart/src/charts/scatterChart.ts, apps/chart/src/component/plot.ts, apps/chart/src/store/plot.ts, apps/chart/stories/plot.stories.ts, apps/chart/tests/components/plot.spec.ts, apps/chart/tests/store/plot.spec.ts, apps/chart/types/options.d.ts, apps/chart/types/store/store.d.ts
=> refactor: rename showLine to visible

apps/chart/src/charts/chart.ts
=> fix: destroy frame error

apps/chart/src/store/axes.ts, apps/chart/src/store/legend.ts
=> fix: scatter bug

apps/chart/src/charts/chart.ts, apps/chart/src/component/hoveredSeries.ts, apps/chart/src/component/legend.ts, apps/chart/src/component/selectedSeries.ts, apps/chart/src/component/zoom.ts, apps/chart/src/store/reactive.ts
=> refactor: change observable object to normal object before return

examples/example05-01-bubble-chart-basic.html, package-lock.json
=> refactor: fix typo operators

apps/chart/src/brushes/lineSeries.ts, apps/chart/src/charts/lineChart.ts, apps/chart/src/component/areaSeries.ts, apps/chart/src/component/component.ts, apps/chart/src/component/lineSeries.ts, apps/chart/src/helpers/calculator.ts, apps/chart/src/store/dataRange.ts, apps/chart/stories/area.stories.ts, apps/chart/stories/data.ts, apps/chart/stories/line.stories.ts, apps/chart/tests/components/areaSeries.spec.ts, apps/chart/tests/components/lineSeries.spec.ts, apps/chart/types/components/series.d.ts, apps/chart/types/options.d.ts
=> fix: line area null data

apps/chart/src/component/heatmapSeries.ts, apps/chart/src/helpers/colorSpectrum.ts, apps/chart/src/helpers/downloader.ts, apps/chart/src/store/treemapSeriesData.ts, apps/chart/stories/data.ts, apps/chart/stories/heatmap.stories.ts, apps/chart/stories/treemap.stories.ts, apps/chart/tests/components/heatmapSeries.spec.ts, apps/chart/tests/components/treemapSeries.spec.ts, apps/chart/types/components/series.d.ts, apps/chart/types/options.d.ts, apps/chart/types/store/store.d.ts
=> fix: treemap heatmap null data

apps/chart/src/component/bubbleSeries.ts, apps/chart/src/component/scatterSeries.ts, apps/chart/src/helpers/downloader.ts, apps/chart/src/store/category.ts, apps/chart/src/store/dataRange.ts, apps/chart/stories/bubble.stories.ts, apps/chart/stories/data.ts, apps/chart/stories/scatter.stories.ts, apps/chart/tests/components/bubbleSeries.spec.ts, apps/chart/tests/components/scatterSeries.spec.ts, apps/chart/types/options.d.ts
=> fix: scatter bubble null data

apps/chart/src/component/tooltip.ts, apps/chart/src/store/axes.ts, apps/chart/stories/axes.stories.ts, apps/chart/types/options.d.ts
=> feat: axis formatter

apps/chart/stories/area.stories.ts, apps/chart/stories/axes.stories.ts, apps/chart/stories/bar.groupstack.stories.ts, apps/chart/stories/bar.stack.stories.ts, apps/chart/stories/bar.stories.ts, apps/chart/stories/boxPlot.stories.ts, apps/chart/stories/bubble.stories.ts, apps/chart/stories/bullet.stories.ts, apps/chart/stories/circleLegend.stories.ts, apps/chart/stories/column.groupstack.stories.ts, apps/chart/stories/column.stack.stories.ts, apps/chart/stories/column.stories.ts, apps/chart/stories/columnLine.stories.ts, apps/chart/stories/heatmap.stories.ts, apps/chart/stories/layout.stories.ts, apps/chart/stories/line.stories.ts, apps/chart/stories/lineArea.stories.ts, apps/chart/stories/lineScatter.stories.ts, apps/chart/stories/nestedPie.stories.ts, apps/chart/stories/pie.stories.ts, apps/chart/stories/plot.stories.ts, apps/chart/stories/radar.stories.ts, apps/chart/stories/scatter.stories.ts, apps/chart/stories/spectrumLegend.stories.ts, apps/chart/stories/theme.stories.ts, apps/chart/stories/tooltip.stories.ts, apps/chart/stories/treemap.stories.ts
=> chore: remove red border line on story

apps/chart/src/component/boxSeries.ts, apps/chart/stories/bar.stories.ts, apps/chart/stories/column.stories.ts
**Bar**
| AS-IS | TO-BE |
| --- | --- |
| <img width="993" alt="스크린샷 2021-01-19 18 10 37" src="https://user-images.githubusercontent.com/43128697/105013141-45e7ce80-5a82-11eb-9131-bec0618105a1.png"> | <img width="993" alt="스크린샷 2021-01-19 18 04 48" src="https://user-images.githubusercontent.com/43128697/105013124-41231a80-5a82-11eb-964f-10cec313c9a4.png"> |
**Column**
| AS-IS | TO-BE |
| --- | --- |
| <img width="991" alt="스크린샷 2021-01-19 18 11 36" src="https://user-images.githubusercontent.com/43128697/105013082-38324900-5a82-11eb-80f6-234e8ad2da9c.png"> | <img width="995" alt="스크린샷 2021-01-19 18 06 07" src="https://user-images.githubusercontent.com/43128697/105013066-34062b80-5a82-11eb-8d17-314a79c7e851.png"> |
---
Thank you for your contribution to TOAST UI …
=> fix : range data labels on box series

apps/chart/src/component/pieSeries.ts, apps/chart/src/helpers/downloader.ts, apps/chart/src/helpers/pieSeries.ts, apps/chart/stories/data.ts, apps/chart/stories/nestedPie.stories.ts, apps/chart/stories/pie.stories.ts, apps/chart/tests/components/pieSeries.spec.ts, apps/chart/types/options.d.ts
=> fix: resolve null data for pie series(including nested pie)

apps/chart/src/charts/radarChart.ts, apps/chart/src/component/radarSeries.ts, apps/chart/stories/data.ts, apps/chart/stories/radar.stories.ts, apps/chart/tests/components/radarSeries.spec.ts, apps/chart/types/components/series.d.ts, apps/chart/types/options.d.ts
=> fix: resolve radar series with null data

apps/chart/package.json
```js
import BarChart from '@toast-ui/chart/bar';
import ColumnChart from '@toast-ui/chart/column';
import LineChart from '@toast-ui/chart/line';
import AreaChart from '@toast-ui/chart/area';
import LineAreaChart from '@toast-ui/chart/lineArea';
import ColumnLineChart from '@toast-ui/chart/columnLine';
import BulletChart from '@toast-ui/chart/bullet';
import BoxPlotChart from '@toast-ui/chart/boxPlot';
import TreemapChart from '@toast-ui/chart/treemap';
import HeatmapChart from '@toast-ui/chart/heatmap';
import ScatterChart from '@toast-ui/chart/scatter';
import LineScatterChart from '@toast-ui/chart/lineScatter';
import BubbleChart from '@toast-ui/chart/bubble';
import PieChart from '@toast-ui/chart/pie';
import NestedPieChart from '@toast-ui/chart/nestedPie';
import RadarChart from …
```
=> chore: add exports field in package.json

apps/chart/package-lock.json, apps/chart/package.json, apps/react-chart/package-lock.json, apps/react-chart/package.json, apps/vue-chart/package-lock.json, apps/vue-chart/package.json, lerna.json, package.json
=> beta 2 test

apps/chart/src/component/tooltip.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/heatmapAxes.ts, apps/chart/stories/axes.stories.ts, apps/chart/stories/bar.stories.ts, apps/chart/stories/column.stories.ts, apps/chart/stories/radar.stories.ts, apps/chart/types/index.d.ts, apps/chart/types/options.d.ts, docs/en/common-axes.md, docs/en/common-tooltip.md, docs/ko/common-axes.md, docs/ko/common-tooltip.md
```js
export type TooltipData = {
label: string;
color: string;
value: TooltipDataValue;
formattedValue?: string;
category?: string;
templateType?: TooltipTemplateType;
rootParentName?: string;
percentValue?: number;
index?: number;
seriesIndex?: number;
};
type TooltipFormatter = (value: SeriesDataType, tooltipDataInfo?: TooltipData) => string;
```
```ts
type AxisLabelInfo = { axisName: AxisType; labels: string[]; index: number };
type AxisFormatter = (value: string, axisLabelInfo: AxisLabelInfo) => string;
```
---
=> refactor: add additional info

apps/chart/src/store/reactive.ts
reactive.ts refactor and add comments
---
=> refactor: simpler identification of observers

apps/chart/src/component/tooltip.ts, apps/chart/src/helpers/style.ts, apps/chart/stories/tooltip.stories.ts, apps/chart/types/options.d.ts, docs/en/common-tooltip.md, docs/ko/common-tooltip.md
```js
tooltip: {
transition: true,
transition: false,  // default
transition: 'transform 2s ease-out',
}
}
```
---
=> feat: tooltip transition

apps/chart/src/store/dataRange.ts
| AS-IS | TO-BE |
| --- | --- |
| <img width="638" alt="스크린샷 2021-01-21 17 54 24" src="https://user-images.githubusercontent.com/43128697/105327134-e28ca680-5c11-11eb-8867-8a4e362e234b.png"> | <img width="608" alt="스크린샷 2021-01-21 17 52 06" src="https://user-images.githubusercontent.com/43128697/105327163-e91b1e00-5c11-11eb-8c79-50403ecdff92.png"> |
---
=> fix: resolve radar chart when legend active event

apps/chart/src/component/axis.ts, apps/chart/src/component/boxSeries.ts, apps/chart/src/component/pieSeries.ts, apps/chart/src/helpers/axes.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/heatmapAxes.ts, apps/chart/src/store/layout.ts, apps/chart/stories/axes.stories.ts, apps/chart/tests/components/axes.spec.ts, apps/chart/types/options.d.ts, docs/en/common-axes.md, docs/ko/common-axes.md
```js
xAxis: {
label: {
margin: 10
}
},
yAxis: {
label: {
margin: 10
}
}
}
```
---
=> feat: label margin

apps/chart/src/brushes/basic.ts, apps/chart/src/brushes/label.ts, apps/chart/src/component/bulletSeries.ts, apps/chart/src/store/category.ts, apps/chart/src/store/dataRange.ts
=> perf: remove transparent

apps/chart/src/component/axis.ts, apps/chart/src/component/zoom.ts
* reset hovered, selected series after zoom
---
=> fix: remove hovered, selected series after zoom

apps/chart/src/helpers/axes.ts, apps/chart/src/store/axes.ts, apps/chart/tests/store/axes.spec.ts
check category width before calculate auto
---
=> refactor: add axes auto logic

README.md, apps/chart/README.md, apps/chart/package-lock.json, apps/chart/package.json, apps/react-chart/package-lock.json, apps/react-chart/package.json, apps/vue-chart/package-lock.json, apps/vue-chart/package.json, lerna.json
=> chore: Beta 3

.github/ISSUE_TEMPLATE/question.md, CONTRIBUTING.md, README.md, apps/react-chart/README.md, apps/vue-chart/README.md, docs/README.md, docs/ko/README.md, docs/v4.0-migration-guide-en.md, docs/v4.0-migration-guide-ko.md
=> docs: update master to main branch

apps/chart/README.md, docs/en/getting-started.md, docs/ko/getting-started.md, docs/v4.0-migration-guide-en.md, docs/v4.0-migration-guide-ko.md
=> docs: add getting started guide

apps/react-chart/README.md, apps/vue-chart/README.md
=> docs: change wrapper link

README.md, docs/README.md, docs/en/chart-area.md, docs/en/chart-bubble.md, docs/en/chart-columnLine.md, docs/en/chart-heatmap.md, docs/en/chart-line.md, docs/en/chart-lineArea.md, docs/en/chart-lineScatter.md, docs/en/chart-nestedPie.md, docs/en/chart-scatter.md, docs/en/chart-treemap.md, docs/en/common-liveUpdate-options.md, docs/ko/chart-area.md, docs/ko/common-liveUpdate-options.md, docs/v4.0-migration-guide-en.md, docs/v4.0-migration-guide-ko.md
=> docs: resolve en links:

docs/en/common-liveUpdate-options.md, docs/ko/chart-bullet.md, docs/ko/chart-heatmap.md, docs/ko/chart-nestedPie.md, docs/ko/common-liveUpdate-options.md
=> docs: fix broken link

apps/chart/src/charts/areaChart.ts, apps/chart/src/charts/barChart.ts, apps/chart/src/charts/boxPlotChart.ts, apps/chart/src/charts/bubbleChart.ts, apps/chart/src/charts/bulletChart.ts, apps/chart/src/charts/chart.ts, apps/chart/src/charts/columnChart.ts, apps/chart/src/charts/columnLineChart.ts, apps/chart/src/charts/heatmapChart.ts, apps/chart/src/charts/lineAreaChart.ts, apps/chart/src/charts/lineChart.ts, apps/chart/src/charts/lineScatterChart.ts, apps/chart/src/charts/nestedPieChart.ts, apps/chart/src/charts/pieChart.ts, apps/chart/src/charts/radarChart.ts, apps/chart/src/charts/scatterChart.ts, apps/chart/src/charts/treemapChart.ts, apps/chart/src/component/selectedSeries.ts
=> fix: reset series

apps/chart/src/component/exportMenu.ts, apps/chart/src/component/tooltip.ts, apps/chart/src/css/chart.css, apps/chart/src/helpers/tooltipTemplate.ts
* add prefix `toastui-chart`
---
=> fix: add prefix toastui-chart

src/js/components/tooltips/groupTooltip.js, src/js/components/tooltips/mapChartTooltip.js, src/js/components/tooltips/normalTooltip.js
=> refactor: add color info for custom tooltip

src/js/components/series/lineTypeSeriesBase.js, src/js/models/data/dataProcessor.js, src/js/plugins/raphaelAreaChart.js
* Line type chart null data dataLabel exposed properly
---
=> fix: line type null data labels

apps/chart/package.json
=> chore: update sideeffects setting

apps/chart/src/charts/areaChart.ts, apps/chart/src/charts/barChart.ts, apps/chart/src/charts/boxPlotChart.ts, apps/chart/src/charts/bubbleChart.ts, apps/chart/src/charts/bulletChart.ts, apps/chart/src/charts/chart.ts, apps/chart/src/charts/columnChart.ts, apps/chart/src/charts/columnLineChart.ts, apps/chart/src/charts/heatmapChart.ts, apps/chart/src/charts/lineAreaChart.ts, apps/chart/src/charts/lineChart.ts, apps/chart/src/charts/lineScatterChart.ts, apps/chart/src/charts/nestedPieChart.ts, apps/chart/src/charts/radarChart.ts, apps/chart/src/charts/scatterChart.ts, apps/chart/src/charts/treemapChart.ts, apps/chart/types/options.d.ts
```
const chart = new Chart({ ... });
chart.setData({
// When calling API immediately after creation
});
```
---
=> fix: remove settimeout when initialize

docs/en/common-axes.md, docs/ko/common-axes.md
=> docs: add secondary y axis guide

apps/chart/types/components/axis.d.ts, apps/chart/types/components/dataLabels.d.ts, apps/chart/types/components/exportMenu.d.ts, apps/chart/types/components/legend.d.ts, apps/chart/types/components/plot.d.ts, apps/chart/types/components/series.d.ts, apps/chart/types/components/spectrumLegend.d.ts, apps/chart/types/components/zoom.d.ts, apps/chart/types/index.d.ts, apps/chart/types/options.d.ts, apps/chart/types/store/store.d.ts, apps/chart/types/theme.d.ts
=> chore: remove alias(#561)

apps/chart/examples/example01-11-area-chart-responsive.html, apps/chart/examples/example02-08-bar-chart-responsive.html, apps/chart/examples/example03-03-boxPlot-chart-responsive.html, apps/chart/examples/example04-03-bubble-chart-responsive.html, apps/chart/examples/example06-08-column-chart-responsive.html, apps/chart/examples/example07-05-heatmap-chart-responsive.html, apps/chart/examples/example08-10-line-chart-responsive.html, apps/chart/examples/example09-08-pie-chart-responsive.html, apps/chart/examples/example10-05-radar-chart-responsive.html, apps/chart/examples/example11-03-scatter-chart-responsive.html, apps/chart/examples/example12-06-treemap-chart-responsive.html, apps/chart/src/charts/chart.ts, apps/chart/src/component/exportMenu.ts, apps/chart/src/store/root.ts
=> fix: ie10 bugs

apps/chart/stories/radialBar.stories.ts, apps/chart/types/options.d.ts
* add null, visible types for radialBar chart
---
=> chore: add types for radialBar chart visible, null data

apps/chart/examples/example08-05-line-chart-coordinate-data.html, apps/chart/examples/example08-06-line-chart-dateTimeTuple-data.html, apps/chart/src/helpers/coordinate.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/dataRange.ts, apps/chart/src/store/scale.ts, apps/chart/tests/store/axes.spec.ts, apps/chart/tests/store/dataRange.spec.ts, apps/chart/tests/store/scale.spec.ts
=> fix: check coordinate type with initStoreState (#591)

apps/react-chart/README.md, apps/react-chart/index.d.ts, apps/react-chart/src/base.js, apps/react-chart/stories/options.stories.js, apps/vue-chart/README.md, apps/vue-chart/stories/options.stories.js
=> fix: wrapper responsive

apps/chart/examples/example18-01-radialBar-chart-basic.html, apps/chart/src/charts/barChart.ts, apps/chart/src/charts/chart.ts, apps/chart/src/charts/columnChart.ts, apps/chart/src/component/boxSeries.ts, apps/chart/src/store/layout.ts, apps/chart/src/store/scale.ts, apps/chart/stories/area.stories.ts, apps/chart/stories/bar.groupstack.stories.ts, apps/chart/stories/bar.stack.stories.ts, apps/chart/stories/bar.stories.ts, apps/chart/stories/boxPlot.stories.ts, apps/chart/stories/bubble.stories.ts, apps/chart/stories/bullet.stories.ts, apps/chart/stories/column.groupstack.stories.ts, apps/chart/stories/column.stack.stories.ts, apps/chart/stories/column.stories.ts, apps/chart/stories/columnLine.stories.ts, apps/chart/stories/heatmap.stories.ts, apps/chart/stories/line.stories.ts, apps/chart/stories/lineArea.stories.ts, apps/chart/stories/lineScatter.stories.ts, apps/chart/stories/nestedPie.stories.ts, apps/chart/stories/pie.stories.ts, apps/chart/stories/radar.stories.ts, apps/chart/stories/radialBar.stories.ts, apps/chart/stories/scatter.stories.ts, apps/chart/stories/treemap.stories.ts, apps/chart/stories/util.ts, apps/chart/types/options.d.ts
=> fix: resolve init animation with responsive

apps/chart/stories/brush.stories.ts
=> fix: change model to render properly

apps/chart/src/charts/chart.ts
=> fix: scale mousepoint(#550)

.github/auto_assign.yml
=> chore: add auto assign actions

.github/auto_assign.yml
=> chore: off assignee

.github/auto_assign.yml
=> chore: set numberOfReviewers 0

apps/chart/src/component/tooltip.ts, apps/chart/src/helpers/dom.ts, apps/chart/src/helpers/htmlSanitizer.ts, apps/chart/src/helpers/utils.ts
#604 
Modification of type and removal of comments after PR merge.
---
=> refactor: change type, remove comment private method

apps/chart/src/helpers/legend.ts, apps/chart/src/store/layout.ts, apps/chart/src/store/legend.ts, apps/chart/stories/heatmap.stories.ts, apps/chart/tests/store/legend.spec.ts
spectrum legend - normal legend
Separate logic that was being calculated together in the store.(legend / spectrum legend)
---
=> refactor: divide legend store logic

apps/chart/src/component/boxSeries.ts, apps/chart/src/component/component.ts, apps/chart/src/store/seriesData.ts
Fixed a problem that charts were not rendered properly when `setData` in no data bar, column, radial bar, nested pie chart .
---
=> Fix: no data set data(#627)

apps/react-chart/src/base.js, apps/react-chart/src/index.js, apps/react-chart/stories/chart.stories.js, apps/react-chart/stories/data.js, apps/vue-chart/src/base.js, apps/vue-chart/src/index.js, apps/vue-chart/stories/chart.stories.js, apps/vue-chart/stories/data.js
* related: #619 
* webpack issue: https://github.com/webpack/webpack/issues/12995
---
=> fix: use default export for webpack5 wrapper(#619)

apps/chart/src/component/areaSeries.ts, apps/chart/src/component/bubbleSeries.ts, apps/chart/src/component/lineSeries.ts, apps/chart/src/component/scatterSeries.ts, apps/chart/src/component/treemapSeries.ts
=> fix: apply theme when select series

apps/chart/src/helpers/theme.ts
=> refactor: refactor series default theme

apps/chart/src/helpers/axes.ts, apps/chart/src/helpers/calculator.ts, apps/chart/src/scale/coordinateScaleCalculator.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/heatmapAxes.ts
=> fix: render chart properly use not formatted label

apps/react-chart/src/index.js, apps/react-chart/stories/chart.stories.js, apps/react-chart/stories/data.js, apps/vue-chart/src/index.js, apps/vue-chart/stories/chart.stories.js, apps/vue-chart/stories/data.js
* feat: apply gauge chart for wrappers
---
=> feat: apply gauge chart for wrappers

apps/chart/package.json, apps/chart/src/helpers/theme.ts, apps/chart/src/index.ts, apps/chart/types/index.d.ts
* fix: add export types
* fix: resolve theme bug
---
=> fix: add export types and resolve theme bug

apps/chart/src/component/bulletSeries.ts, apps/chart/src/store/dataRange.ts, apps/chart/stories/bullet.stories.ts, apps/chart/stories/data.ts, apps/chart/tests/components/bulletSeries.spec.ts, apps/chart/types/components/series.d.ts
#602 
**asis**
**tobe**
**asis**
**tobe**
---
=> fix: bullet bug

apps/chart/src/helpers/downloader.ts, apps/chart/src/store/seriesData.ts
After the data is changed, the reflected data should be downloaded when downloading.
---
=> fix: apply series for new data download

apps/chart/src/store/heatmapAxes.ts
=> fix: apply title according to axis type

apps/chart/src/component/plot.ts, apps/chart/src/component/scatterSeries.ts, apps/chart/src/store/axes.ts, apps/chart/src/store/heatmapAxes.ts
asis
tobe
use `labelRange` only line scatter chart
---
=> fix: use labelRange only line scatter chart

apps/chart/examples/example14-03-LineArea-chart-liveUpdate.html
=> chore: add missing options

apps/chart/types/store/store.d.ts
* remove unnecessary comments
---
=> chore: remove unnecessary commnet

apps/chart/src/component/exportMenu.ts, apps/chart/src/painter.ts
=> fix: resolve chart canvas background transparent (#653)

apps/chart/src/helpers/downloader.ts
=> fix: resolve exporting data for coordinate object type (#656)

apps/map-chart/src/brushes/geoFeature.ts, apps/map-chart/src/chart.ts, apps/map-chart/src/component/hoveredSeries.ts, apps/map-chart/src/component/series.ts, apps/map-chart/src/painter.ts, apps/map-chart/src/store/series.ts, apps/map-chart/stories/world.stories.ts
=> feat: map/hovered series

apps/chart/src/component/exportMenu.ts
Prevent an error when clicking on the title in the export menu
---
=> fix: prevent an error when clicking on the title in the export menu

apps/chart/src/component/pieSeries.ts, apps/chart/tests/components/pieSeries.spec.ts
=> fix: do not make pie series model of zero value data

docs/en/getting-started.md, docs/ko/getting-started.md
* related issue #690 
* update `getting-started.md` page to remove errors that occur when running the example code.
---
=> docs: update getting started page 

.github/stale.yml, LICENSE, README.md, apps/chart/package.json, apps/chart/tuidoc.config.json, apps/map-chart/package.json, apps/react-chart/README.md, apps/react-chart/package.json, apps/shared/package.json, apps/vue-chart/README.md, apps/vue-chart/package.json
* Rename the corporation name to "NHN Cloud"
---
=> docs: rename corp name to NHN Cloud

apps/vue-chart/demo/index.html, apps/vue-chart/demo/index.js, apps/vue-chart/src/base.js
Add missed interface 'rangeSelection' to vue-chart
---
=> fix: add interface for 'rangeSelection' to vue-chart

apps/chart/src/helpers/downloader.ts
Fix the problem that when a user exports csv from firefox, the table is not normally formed as shown in the figure below.
---
=> fix: problem when exporting csv from firefox in compliance with data URL spec
